#JDBC\u914d\u7f6e
spring:
  profiles: default
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/consult
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    max-active: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    alidation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)



custom:
  datasource:
    names: ds1,ds2
    ds1:
      url: jdbc:mysql://localhost:3306/db1
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    ds2:
      url: jdbc:mysql://localhost:3306/db2
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.example.bean
  mapperLocations: classpath*:com.example.mapper/*Mapper.xml
debug: true

